<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>Offload</RootNamespace>
    <AssemblyName>Offload</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Offload.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Offload.Core/Offload.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Offload.ico" />
  </ItemGroup>
</Project>
